<?php
/* $Id: SMTPServer.php 4469 2011-01-15 02:28:37Z daintree $*/
include('includes/session.inc');
$Title = _('SMTP Server details');
include('includes/header.inc');
 
echo '<p class="page_title_text"><img src="' . $RootPath . '/css/' . $Theme . '/images/email.gif" title="' . _('SMTP Server') . '" alt="" />' . ' ' . _('SMTP Server Settings') . '</p>';
// First check if there are smtp server data or not

function testconnection(){
$ConfirmationText = _('Please ignore this email. It was generated by the ERP system you have installed to test the connection');
$EmailSubject = _('ERP SMPT SETTINGS TEST');
   //Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;
//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';
//Set the hostname of the mail server
$mail->Host = $_POST['Host'] ;//"smtp.mail.yahoo.com";
//Set the SMTP port number - likely to be 25, 465 or 587
$mail->Port =$_POST['Port']; //587;
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication
$mail->Username = $_POST['UserName'];
//Password to use for SMTP authentication
$mail->Password = $_POST['Password'];
//Set who the message is to be sent from
 $mail->setFrom($_POST['UserName'], 'System Administrator');
//Set an alternative reply-to address
 $mail->addReplyTo($_POST['UserName'], 'No-Reply');
//Set who the message is to be sent to
$mail->addAddress($_POST['UserName'], 'Admin');
//Set the subject line
$mail->Subject = $EmailSubject;
$mail->Body=$ConfirmationText ;

//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
//$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
//Replace the plain text body with one created manually
$mail->AltBody = $ConfirmationText ;
//Attach an image file
$mail->addAttachment('Mailer/examples/images/phpmailer_mini.png');
$success = $mail->send();
//send the message, check for errors
    if (!$success) {
        echo "Mailer Error: " . $mail->ErrorInfo;
    } else {
        echo "Message sent!";
    }

    return $success;
}




if (isset($_POST['submit']) 
        AND  $_POST['MailServerSetting']==1 
        and  testconnection()) {
//If there are already data setup, Update the table
    
	$sql="UPDATE emailsettings SET
                host='".$_POST['Host']."',
                port='".$_POST['Port']."',
                heloaddress='".$_POST['HeloAddress']."',
                username='".$_POST['UserName']."',
                password='".$_POST['Password']."',
                auth='".$_POST['Auth']."'";

	$ErrMsg = _('The email setting information failed to update');
	$DbgMsg = _('The SQL failed to update is ');
	$result1=DB_query($sql, $db, $ErrMsg, $DbgMsg);
	unset($_POST['MailServerSetting']);
	prnMsg(_('The settings for the SMTP server have been successfully updated'), 'success');
	echo '<br />';

}elseif(isset($_POST['submit']) 
        and $_POST['MailServerSetting']==0 
        and testconnection()){
//There is no data setup yet
	$sql = "INSERT INTO emailsettings(
                        host,
                        port,
                        heloaddress,
                        username,
                        password,
                        auth)
                    VALUES ('".$_POST['Host']."',
                            '".$_POST['Port']."',
                            '".$_POST['HeloAddress']."',
                            '".$_POST['UserName']."',
                            '".$_POST['Password']."',
                            '".$_POST['Auth']."')";
	$ErrMsg = _('The email settings failed to be inserted');
	$DbgMsg = _('The SQL failed to insert the email information is');
	$result2 = DB_query($sql,$db);
	unset($_POST['MailServerSetting']);
	prnMsg(_('The settings for the SMTP server have been sucessfully inserted'),'success');
	echo '<br/>';
}

  // Check the mail server setting status

		$sql="SELECT  id,
				host,
				port,
				heloaddress,
				username,
				password,
				timeout,
				auth
			FROM emailsettings";
		$ErrMsg = _('The email settings information cannot be retrieved');
		$DbgMsg = _('The SQL that failed was');

		$result=DB_query($sql, $db,$ErrMsg,$DbgMsg);
		if(DB_num_rows($result)!=0){
			$MailServerSetting = 1;
			$myrow=DB_fetch_array($result);
		}else{
			DB_free_result($result);
			$MailServerSetting = 0;
			$myrow['host']='smtp.mail.yahoo.com';
			$myrow['port']='587';
			$myrow['heloaddress']='elo';
			$myrow['username']='';
			$myrow['password']='';
                        $myrow['auth']=1;
			$myrow['timeout']=30;
		}


echo '<form autocomplete="off"method="post" action="' . htmlspecialchars($_SERVER['PHP_SELF'],ENT_QUOTES,'UTF-8') . '">
	<div>
	<input type="hidden" name="FormID" value="' . $_SESSION['FormID'] . '" />
	<input type="hidden" name="MailServerSetting" value="' . $MailServerSetting . '" />
	<table class="table table-bordered">
	<tr>
		<td>' . _('Server Host Name') . '</td>
		<td><input type="text" name="Host" required="required" value="' . $myrow['host'] . '" /></td>
	</tr>
	<tr>
		<td>' . _('SMTP port') . '</td>
		<td><input type="text" name="Port" required="required" size="4" class="number" value="' . $myrow['port'].'" /></td>
	</tr>
	<tr>
		<td>' . _('Helo Command') . '</td>
		<td><input type="text" name="HeloAddress" value="' . $myrow['heloaddress'] . '" /></td>
	</tr>
	<tr>
		<td>' . _('Authorisation Required') . '</td>
		<td><select name="Auth">';
if ($myrow['auth']==1) {
	echo '<option selected="selected" value="1">' . _('True') . '</option>';
	echo '<option value="0">' . _('False') . '</option>';
} else {
	echo '<option value="1">' . _('True') . '</option>';
	echo '<option selected="selected" value="0">' . _('False') . '</option>';
}
echo '</select></td>
	</tr>
	<tr>
		<td>' . _('User Name') . '</td>
		<td><input type="text" required="required" name="UserName" size="50" maxlength="50" value="' . $myrow['username']  .'" /></td>
	</tr>
	<tr>
		<td>' . _('Password') . '</td>
		<td><input type="password" required="required" name="Password" value="' . $myrow['password'] . '" /></td>
	</tr>
	<tr>
		<td>' . _('Timeout (seconds)') . '</td>
		<td><input type="text" size="5" name="Timeout" class="number" value="' . $myrow['timeout'] . '" /></td>
	</tr>
	<tr>
		<td colspan="2"><div class="centre"><input type="submit" name="submit" value="' . _('Update') . '" /></div></td>
	</tr>
	</table>
	</div>
	</form>';

include('includes/footer.inc');

?>
